Base: []
Landmarks: []
RestrictedZones:
- constraints:
    max_altitude: 100.0
    max_angular_velocity: 2.0
    max_linear_velocity: 10.0
    min_altitude: 0.0
    min_angular_velocity: 0.5
    min_linear_velocity: 1.0
  id: restricted_zone_1
  primitives:
  - center:
    - 1
    - 1
    radius: 0.5
    type: circle
